### ISSUE TITLE
BatteryLevel 101%

### ISSUE THREAD

**Issue by karamo** [Affirmatech/MeshSense#15]
The `"batteryLevel": 101` is a magic number and means **USB powered**

**Comment by scruplelesswizard** [comment]
[Meshtastic Firmware Reference](https://github.com/meshtastic/firmware/blob/c50df710bad0fbdd97093df19de20c75e7ea8c0d/src/PowerStatus.h#L61-L73)

**Comment by mblauser** [comment]
What suggestion do you have for representing this?  Perhaps replacing the battery% with a 🔌 icon/emoji?  
The voltage is still reported while on external power, so that could still remain as-is.

**Comment by karamo** [comment]
Yes, I prefere a symbol for this case. And in the Voltage-field a "-".
A negative voltage ist sensless. The voltage value ist undefined in the FW.

**Comment by N3FJP** [comment]
Hi Guys, thanks so much for your chiming in and supporting MeshSense!  Two thoughts...

-  We can not conclude that a node is grid powered because it reached 101% power level.  While that may be the convention, it isn't accurate.  We have multiple, solar powered nodes that are often at 101% on our network, so displaying a plug would be misleading.  Displaying a plug when a node is solar powered can cause new folks, casually looking at our network, to believe that some of our nodes require commercial power, should an emergency event occur, when they really do not.

-  Voltage should always be displayed regardless.  Wisblocks seem to charge batteries to about 4.2V max and Lilygo boards to 4.5V max by default, but it is important and useful to continue to monitor and display the battery voltages, in case the boards are no longer charge controlling properly, etc.

Thanks again!

**Comment by mblauser** [comment]
I tend to agree with not using 🔌 as it could be inappropriate for solar nodes. It is easier and most scalable to use a unicode symbol, so perhaps the use of⚡️⚡︎ or ⌁ is better suited.

**Comment by mblauser** [comment]
I have introduced draft pull request #17 replacing 101% with a ⚡︎ unicode symbol.  If it seems agreeable to the majority, I'll close the draft and queue it for proposed adoption.

**Comment by Soltares** [comment]
Closing as #17 is included in latest release
